# Settings
title: DecodeMTL | Front-End Coding Bootcamp in Montreal, QC
description: >
  Decode MTL is Montreal’s first & only front-end coding bootcamp.
  Learn HTML, CSS, & Javascript in just 8 weeks. Click here for more info.
